### ISSUE TITLE
Not opensource the storyline

### ISSUE THREAD

**Issue by definev** [tripercy/geminize#11]
Very ảngy 😡

**Comment by tripercy** [comment]
Sorry for your incovinience! Our team are getting to it, thank you for your feedback.

x

**Comment by QuocTranWorkspace** [comment]
ditme thang Duong

**Comment by QuocTranWorkspace** [comment]
close the issue with love<3

**Comment by definev** [comment]
![Screenshot 2024-08-08 at 23 23 12](https://github.com/user-attachments/assets/0f70830c-b48f-41f6-afae-356896891a7a)
🤪🤪🤪
